# [ruff]
line-length = 120
format.quote-style = "single"

# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".ruff_cache",
    ".svn",
    ".tox",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    ".env",
    ".venv",
    "venv",
]

# Assume Python 3.11.
target-version = "py311"

[lint]
# Enable Pyflakes `E` and `F` codes by default.
select = ["E", "F"]
ignore = []
per-file-ignores = {}

[lint.mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10
